server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /open-api
    operationsSorter: method

spring:
  #  security:
  #    user:
  #      name: admin
  #      password: admin

  messages:
    encoding: UTF-8
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      database: logzi
      url: mongodb://localhost:27017
info:
  app:
    name: logzi
    type: SpringBootApplication
    java:
      version: 11

management:
  security:
    enabled: false
    roles: ADMIN
  endpoints:
    health:
      show-details: always
    shutdown:
      enabled: true
    web:
      base-path: /mgmt
      exposure:
        include: "*"

security:
  basic:
    enabled: false
  user:
    name: admin
    password: admin