version: "3"

services:
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo:latest
    expose:
    - 30001
    ports:
      - 30001:30001
    volumes:
       - './data/rs0_mongo1:/data/db:z'
    restart: always
    command: "--bind_ip_all --replSet rs0 --port 30001"
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo:latest
    expose:
    - 30002
    ports:
      - 30002:30002
    volumes:
       - './data/rs0_mongo2:/data/db:z'
    restart: always
    command: "--bind_ip_all --replSet rs0 --port 30002"
  mongo3:
    hostname: mongo3
    container_name: mongo3
    image: mongo:latest
    expose:
    - 30003
    ports:
      - 30003:30003
    volumes:
       - './data/rs0_mongo3:/data/db:z'
    restart: always
    command: "--bind_ip_all --replSet rs0 --port 30003"

volumes:
  rs0_mongo1:
  rs0_mongo2:
  rs0_mongo3: